input:
  tiles: "data/uk_20km_grid.gpkg"
  lsoa_shapefile: "data/uk_lsoa_tiles.gpkg"
  collection: "element84-s2"
  time:
    start_date: "YEAR-01-01"
    end_date: "YEAR-12-31"
  bands_of_interest: [ "cloud", "scl" ]
  input_storage: "embed2social-storage/YEAR"

output:
  out_crs: 27700
  res: 20
  out_dtype: "float32"
  resampling: "nearest"
  output_format: "GTiff"
  time_dim: "year"
  lsoa_output_file: "embed2social-storage/extracted-lsoa-geopackage/YEAR_output.gpkg"
  lsoa_output_format: "geopackage"
  scaling_factor: 32767

dask:
  chunks: { "time": 20, "x": 250, "y": 250 }
  npartitions: 64
  n_workers: 8
  threads_per_worker: 1
  memory_limit: "4GB"
  local_cluster: True
  dashboard_address: 8787
  worker_walltime: "3:00:00"
  job_extra_directives: ["--gres=gpu:0"]
